//Info and Sprite from: 
// https://www.serebii.net/scarletviolet/paldeapokedex.shtml
// https://www.serebii.net/scarletviolet/exclusives.shtml

const pokedex = [
    {
        id: 'dex001',
        dexNumber: '001',
        title: "Sprigatito",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/906.png",
        exclusive: "no",
    },
    {
        id: 'dex002',
        dexNumber: '002',
        title: "Floragato",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/907.png",
        exclusive: "no",
    },
    {
        id: 'dex003',
        dexNumber: '003',
        title: "Meowscarada",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/908.png",
        exclusive: "no",
    },
    {
        id: 'dex004',
        dexNumber: '004',
        title: "Fuecoco",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/909.png",
        exclusive: "no",
    },
    {
        id: 'dex005',
        dexNumber: '005',
        title: "Crocalor",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/910.png",
        exclusive: "no",
    },
    {
        id: 'dex006',
        dexNumber: '006',
        title: "Skeledirge",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/911.png",
        exclusive: "no",
    },
    {
        id: 'dex007',
        dexNumber: '007',
        title: "Quaxly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/912.png",
        exclusive: "no",
    },
    {
        id: 'dex008',
        dexNumber: '008',
        title: "Quaxwell",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/913.png",
        exclusive: "no",
    },
    {
        id: 'dex009',
        dexNumber: '009',
        title: "Quaquaval",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/914.png",
        exclusive: "no",
    },
    {
        id: 'dex010',
        dexNumber: '010',
        title: "Lechonk",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/915.png",
        exclusive: "no",
    },
    {
        id: 'dex011',
        dexNumber: '011',
        title: "Oinkologne",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/916.png",
        exclusive: "no",
    },
    {
        id: 'dex012',
        dexNumber: '012',
        title: "Tarountula",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/918.png",
        exclusive: "no",
    },
    {
        id: 'dex013',
        dexNumber: '013',
        title: "Spidops",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/919.png",
        exclusive: "no",
    },
    {
        id: 'dex014',
        dexNumber: '014',
        title: "Nymble",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/920.png",
        exclusive: "no",
    },
    {
        id: 'dex015',
        dexNumber: '015',
        title: "Lokix",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/921.png",
        exclusive: "no",
    },
    {
        id: 'dex016',
        dexNumber: '016',
        title: "Hoppip",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/187.png",
        exclusive: "no",
    },
    {
        id: 'dex017',
        dexNumber: '017',
        title: "Skiploom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/188.png",
        exclusive: "no",
    },
    {
        id: 'dex018',
        dexNumber: '018',
        title: "Jumpluff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/189.png",
        exclusive: "no",
    },
    {
        id: 'dex019',
        dexNumber: '019',
        title: "Fletchling",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/661.png",
        exclusive: "no",
    },
    {
        id: 'dex020',
        dexNumber: '020',
        title: "Fletchinder",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/662.png",
        exclusive: "no",
    },
    {
        id: 'dex021',
        dexNumber: '021',
        title: "Talonflame",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/663.png",
        exclusive: "no",
    },
    {
        id: 'dex022',
        dexNumber: '022',
        title: "Pawmi",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/954.png",
        exclusive: "no",
    },
    {
        id: 'dex023',
        dexNumber: '023',
        title: "Pawmo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/955.png",
        exclusive: "no",
    },
    {
        id: 'dex024',
        dexNumber: '024',
        title: "Pawmot",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/956.png",
        exclusive: "no",
    },
    {
        id: 'dex025',
        dexNumber: '025',
        title: "Houndour",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/228.png",
        exclusive: "no",
    },
    {
        id: 'dex026',
        dexNumber: '026',
        title: "Houndoom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/229.png",
        exclusive: "no",
    },
    {
        id: 'dex027',
        dexNumber: '027',
        title: "Yungoos",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/734.png",
        exclusive: "no",
    },
    {
        id: 'dex028',
        dexNumber: '028',
        title: "Gumshoos",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/735.png",
        exclusive: "no",
    },
    {
        id: 'dex029',
        dexNumber: '029',
        title: "Skwovet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/819.png",
        exclusive: "no",
    },
    {
        id: 'dex030',
        dexNumber: '030',
        title: "Greedent",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/820.png",
        exclusive: "no",
    },
    {
        id: 'dex031',
        dexNumber: '031',
        title: "Sunkern",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/191.png",
        exclusive: "no",
    },
    {
        id: 'dex032',
        dexNumber: '032',
        title: "Sunflora",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/192.png",
        exclusive: "no",
    },
    {
        id: 'dex033',
        dexNumber: '033',
        title: "Kricketot",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/401.png",
        exclusive: "no",
    },
    {
        id: 'dex034',
        dexNumber: '034',
        title: "Kricketune",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/402.png",
        exclusive: "no",
    },
    {
        id: 'dex035',
        dexNumber: '035',
        title: "Scatterbug",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/664.png",
        exclusive: "no",
    },
    {
        id: 'dex036',
        dexNumber: '036',
        title: "Spewpa",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/665.png",
        exclusive: "no",
    },
    {
        id: 'dex037',
        dexNumber: '037',
        title: "Vivillon",
        img: "https://www.serebii.net/scarletviolet/pokemon/666-f.png",
        exclusive: "no",
    },
    {
        id: 'dex038',
        dexNumber: '038',
        title: "Combee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/415.png",
        exclusive: "no",
    },
    {
        id: 'dex039',
        dexNumber: '039',
        title: "Vespiquen",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/416.png",
        exclusive: "no",
    },
    {
        id: 'dex040',
        dexNumber: '040',
        title: "Rookidee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/821.png",
        exclusive: "no",
    },
    {
        id: 'dex041',
        dexNumber: '041',
        title: "Corvisquire",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/822.png",
        exclusive: "no",
    },
    {
        id: 'dex042',
        dexNumber: '042',
        title: "Corviknight",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/823.png",
        exclusive: "no",
    },
    {
        id: 'dex043',
        dexNumber: '043',
        title: "Happiny",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/440.png",
        exclusive: "no",
    },
    {
        id: 'dex044',
        dexNumber: '044',
        title: "Chansey",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/113.png",
        exclusive: "no",
    },
    {
        id: 'dex045',
        dexNumber: '045',
        title: "Blissey",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/242.png",
        exclusive: "no",
    },
    {
        id: 'dex046',
        dexNumber: '046',
        title: "Azurill",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/298.png",
        exclusive: "no",
    },
    {
        id: 'dex047',
        dexNumber: '047',
        title: "Marill",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/183.png",
        exclusive: "no",
    },
    {
        id: 'dex048',
        dexNumber: '048',
        title: "Azumarill",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/184.png",
        exclusive: "no",
    },
    {
        id: 'dex049',
        dexNumber: '049',
        title: "Surskit",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/283.png",
        exclusive: "no",
    },
    {
        id: 'dex050',
        dexNumber: '050',
        title: "Masquerain",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/284.png",
        exclusive: "no",
    },
    {
        id: 'dex051',
        dexNumber: '051',
        title: "Buizel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/418.png",
        exclusive: "no",
    },
    {
        id: 'dex052',
        dexNumber: '052',
        title: "Floatzel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/419.png",
        exclusive: "no",
    },
    {
        id: 'dex053',
        dexNumber: '053',
        title: "Wooper",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/194-p.png",
        exclusive: "no",
    },
    {
        id: 'dex054',
        dexNumber: '054',
        title: "Clodsire",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1009.png",
        exclusive: "no",
    },
    {
        id: 'dex055',
        dexNumber: '055',
        title: "Psyduck",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/054.png",
        exclusive: "no",
    },
    {
        id: 'dex056',
        dexNumber: '056',
        title: "Golduck",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/055.png",
        exclusive: "no",
    },
    {
        id: 'dex057',
        dexNumber: '057',
        title: "Chewtle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/833.png",
        exclusive: "no",
    },
    {
        id: 'dex058',
        dexNumber: '058',
        title: "Drednaw",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/834.png",
        exclusive: "no",
    },
    {
        id: 'dex059',
        dexNumber: '059',
        title: "Igglybuff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/174.png",
        exclusive: "no",
    },
    {
        id: 'dex060',
        dexNumber: '060',
        title: "Jigglypuff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/039.png",
        exclusive: "no",
    },
    {
        id: 'dex061',
        dexNumber: '061',
        title: "Wigglytuff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/040.png",
        exclusive: "no",
    },
    {
        id: 'dex062',
        dexNumber: '062',
        title: "Ralts",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/280.png",
        exclusive: "no",
    },
    {
        id: 'dex063',
        dexNumber: '063',
        title: "Kirlia",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/281.png",
        exclusive: "no",
    },
    {
        id: 'dex064',
        dexNumber: '064',
        title: "Gardevoir",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/282.png",
        exclusive: "no",
    },
    {
        id: 'dex065',
        dexNumber: '065',
        title: "Gallade",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/475.png",
        exclusive: "no",
    },
    {
        id: 'dex066',
        dexNumber: '066',
        title: "Drowzee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/096.png",
        exclusive: "no",
    },
    {
        id: 'dex067',
        dexNumber: '067',
        title: "Hypno",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/097.png",
        exclusive: "no",
    },
    {
        id: 'dex068',
        dexNumber: '068',
        title: "Gastly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/092.png",
        exclusive: "no",
    },
    {
        id: 'dex069',
        dexNumber: '069',
        title: "Haunter",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/093.png",
        exclusive: "no",
    },
    {
        id: 'dex070',
        dexNumber: '070',
        title: "Gengar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/094.png",
        exclusive: "no",
    },
    {
        id: 'dex071',
        dexNumber: '071',
        title: "Tandemaus",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/945.png",
        exclusive: "no",
    },
    {
        id: 'dex072',
        dexNumber: '072',
        title: "Maushold",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/946.png",
        exclusive: "no",
    },
    {
        id: 'dex073',
        dexNumber: '073',
        title: "Pichu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/172.png",
        exclusive: "no",
    },
    {
        id: 'dex074',
        dexNumber: '074',
        title: "Pikachu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/025.png",
        exclusive: "no",
    },
    {
        id: 'dex075',
        dexNumber: '075',
        title: "Raichu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/026.png",
        exclusive: "no",
    },
    {
        id: 'dex076',
        dexNumber: '076',
        title: "Fidough",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/970.png",
        exclusive: "no",
    },
    {
        id: 'dex077',
        dexNumber: '077',
        title: "Dachsbun",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/971.png",
        exclusive: "no",
    },
    {
        id: 'dex078',
        dexNumber: '078',
        title: "Slakoth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/287.png",
        exclusive: "no",
    },
    {
        id: 'dex079',
        dexNumber: '079',
        title: "Vigoroth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/288.png",
        exclusive: "no",
    },
    {
        id: 'dex080',
        dexNumber: '080',
        title: "Slaking",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/289.png",
        exclusive: "no",
    },
    {
        id: 'dex081',
        dexNumber: '081',
        title: "Bounsweet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/761.png",
        exclusive: "no",
    },
    {
        id: 'dex082',
        dexNumber: '082',
        title: "Steenee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/762.png",
        exclusive: "no",
    },
    {
        id: 'dex083',
        dexNumber: '083',
        title: "Tsareena",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/763.png",
        exclusive: "no",
    },
    {
        id: 'dex084',
        dexNumber: '084',
        title: "Smoliv",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/935.png",
        exclusive: "no",
    },
    {
        id: 'dex085',
        dexNumber: '085',
        title: "Dolliv",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/936.png",
        exclusive: "no",
    },
    {
        id: 'dex086',
        dexNumber: '086',
        title: "Arboliva",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/937.png",
        exclusive: "no",
    },
    {
        id: 'dex087',
        dexNumber: '087',
        title: "Bonsly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/438.png",
        exclusive: "no",
    },
    {
        id: 'dex088',
        dexNumber: '088',
        title: "Sudowoodo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/185.png",
        exclusive: "no",
    },
    {
        id: 'dex089',
        dexNumber: '089',
        title: "Rockruff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/744.png",
        exclusive: "no",
    },
    {
        id: 'dex090',
        dexNumber: '090',
        title: "Lycanroc",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/745.png",
        exclusive: "no",
    },
    {
        id: 'dex091',
        dexNumber: '091',
        title: "Rolycoly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/837.png",
        exclusive: "no",
    },
    {
        id: 'dex092',
        dexNumber: '092',
        title: "Carkol",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/838.png",
        exclusive: "no",
    },
    {
        id: 'dex093',
        dexNumber: '093',
        title: "Coalossal",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/839.png",
        exclusive: "no",
    },
    {
        id: 'dex094',
        dexNumber: '094',
        title: "Shinx",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/403.png",
        exclusive: "no",
    },
    {
        id: 'dex095',
        dexNumber: '095',
        title: "Luxio",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/404.png",
        exclusive: "no",
    },
    {
        id: 'dex096',
        dexNumber: '096',
        title: "Luxray",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/405.png",
        exclusive: "no",
    },
    {
        id: 'dex097',
        dexNumber: '097',
        title: "Starly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/396.png",
        exclusive: "no",
    },
    {
        id: 'dex098',
        dexNumber: '098',
        title: "Staravia",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/397.png",
        exclusive: "no",
    },
    {
        id: 'dex099',
        dexNumber: '099',
        title: "Staraptor",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/398.png",
        exclusive: "no",
    },
    {
        id: 'dex100',
        dexNumber: '100',
        title: "Oricorio",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/741.png",
        exclusive: "no",
    },
    {
        id: 'dex101',
        dexNumber: '101',
        title: "Mareep",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/179.png",
        exclusive: "no",
    },
    {
        id: 'dex102',
        dexNumber: '102',
        title: "Flaaffy",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/180.png",
        exclusive: "no",
    },
    {
        id: 'dex103',
        dexNumber: '103',
        title: "Ampharos",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/181.png",
        exclusive: "no",
    },
    {
        id: 'dex104',
        dexNumber: '104',
        title: "Petilil",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/548.png",
        exclusive: "no",
    },
    {
        id: 'dex105',
        dexNumber: '105',
        title: "Lilligant",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/549.png",
        exclusive: "no",
    },
    {
        id: 'dex106',
        dexNumber: '106',
        title: "Shroomish",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/285.png",
        exclusive: "no",
    },
    {
        id: 'dex107',
        dexNumber: '107',
        title: "Breloom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/286.png",
        exclusive: "no",
    },
    {
        id: 'dex108',
        dexNumber: '108',
        title: "Applin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/840.png",
        exclusive: "no",
    },
    {
        id: 'dex109',
        dexNumber: '109',
        title: "Flapple",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/841.png",
        exclusive: "no",
    },
    {
        id: 'dex110',
        dexNumber: '110',
        title: "Appletun",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/842.png",
        exclusive: "no",
    },
    {
        id: 'dex111',
        dexNumber: '111',
        title: "Spoink",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/325.png",
        exclusive: "no",
    },
    {
        id: 'dex112',
        dexNumber: '112',
        title: "Grumpig",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/326.png",
        exclusive: "no",
    },
    {
        id: 'dex113',
        dexNumber: '113',
        title: "Squawkabilly",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/960.png",
        exclusive: "no",
    },
    {
        id: 'dex114',
        dexNumber: '114',
        title: "Misdreavus",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/200.png",
        exclusive: "Violet",
    },
    {
        id: 'dex115',
        dexNumber: '115',
        title: "Mismagius",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/429.png",
        exclusive: "Violet",
    },
    {
        id: 'dex116',
        dexNumber: '116',
        title: "Makuhita",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/296.png",
        exclusive: "no",
    },
    {
        id: 'dex117',
        dexNumber: '117',
        title: "Hariyama",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/297.png",
        exclusive: "no",
    },
    {
        id: 'dex118',
        dexNumber: '118',
        title: "Crabrawler",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/739.png",
        exclusive: "no",
    },
    {
        id: 'dex119',
        dexNumber: '119',
        title: "Crabominable",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/740.png",
        exclusive: "no",
    },
    {
        id: 'dex120',
        dexNumber: '120',
        title: "Salandit",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/757.png",
        exclusive: "no",
    },
    {
        id: 'dex121',
        dexNumber: '121',
        title: "Salazzle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/758.png",
        exclusive: "no",
    },
    {
        id: 'dex122',
        dexNumber: '122',
        title: "Phanpy",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/231.png",
        exclusive: "no",
    },
    {
        id: 'dex123',
        dexNumber: '123',
        title: "Donphan",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/232.png",
        exclusive: "no",
    },
    {
        id: 'dex124',
        dexNumber: '124',
        title: "Cufant",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/878.png",
        exclusive: "no",
    },
    {
        id: 'dex125',
        dexNumber: '125',
        title: "Copperajah",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/879.png",
        exclusive: "no",
    },
    {
        id: 'dex126',
        dexNumber: '126',
        title: "Gible",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/443.png",
        exclusive: "no",
    },
    {
        id: 'dex127',
        dexNumber: '127',
        title: "Gabite",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/444.png",
        exclusive: "no",
    },
    {
        id: 'dex128',
        dexNumber: '128',
        title: "Garchomp",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/445.png",
        exclusive: "no",
    },
    {
        id: 'dex129',
        dexNumber: '129',
        title: "Nacli",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/963.png",
        exclusive: "no",
    },
    {
        id: 'dex130',
        dexNumber: '130',
        title: "Naclstack",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/964.png",
        exclusive: "no",
    },
    {
        id: 'dex131',
        dexNumber: '131',
        title: "Garganacl",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/965.png",
        exclusive: "no",
    },
    {
        id: 'dex132',
        dexNumber: '132',
        title: "Wingull",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/278.png",
        exclusive: "no",
    },
    {
        id: 'dex133',
        dexNumber: '133',
        title: "Pelipper",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/279.png",
        exclusive: "no",
    },
    {
        id: 'dex134',
        dexNumber: '134',
        title: "Magikarp",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/129.png",
        exclusive: "no",
    },
    {
        id: 'dex135',
        dexNumber: '135',
        title: "Gyarados",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/130.png",
        exclusive: "no",
    },
    {
        id: 'dex136',
        dexNumber: '136',
        title: "Arrokuda",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/846.png",
        exclusive: "no",
    },
    {
        id: 'dex137',
        dexNumber: '137',
        title: "Barraskewda",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/847.png",
        exclusive: "no",
    },
    {
        id: 'dex138',
        dexNumber: '138',
        title: "Basculin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/550.png",
        exclusive: "no",
    },
    {
        id: 'dex139',
        dexNumber: '139',
        title: "Gulpin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/316.png",
        exclusive: "Violet",
    },
    {
        id: 'dex140',
        dexNumber: '140',
        title: "Swalot",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/317.png",
        exclusive: "Violet",
    },
    {
        id: 'dex141',
        dexNumber: '141',
        title: "Meowth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/052.png",
        exclusive: "no",
    },
    {
        id: 'dex142',
        dexNumber: '142',
        title: "Persian",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/053.png",
        exclusive: "no",
    },
    {
        id: 'dex143',
        dexNumber: '143',
        title: "Drifloon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/425.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex144',
        dexNumber: '144',
        title: "Drifblim",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/426.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex145',
        dexNumber: '145',
        title: "Flabébé",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/669.png",
        exclusive: "no",
    },
    {
        id: 'dex146',
        dexNumber: '146',
        title: "Floette",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/670.png",
        exclusive: "no",
    },
    {
        id: 'dex147',
        dexNumber: '147',
        title: "Florges",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/671.png",
        exclusive: "no",
    },
    {
        id: 'dex148',
        dexNumber: '148',
        title: "Diglett",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/050.png",
        exclusive: "no",
    },
    {
        id: 'dex149',
        dexNumber: '149',
        title: "Dugtrio",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/051.png",
        exclusive: "no",
    },
    {
        id: 'dex150',
        dexNumber: '150',
        title: "Torkoal",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/324.png",
        exclusive: "no",
    },
    {
        id: 'dex151',
        dexNumber: '151',
        title: "Numel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/322.png",
        exclusive: "no",
    },
    {
        id: 'dex152',
        dexNumber: '152',
        title: "Camerupt",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/323.png",
        exclusive: "no",
    },
    {
        id: 'dex153',
        dexNumber: '153',
        title: "Bronzor",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/436.png",
        exclusive: "no",
    },
    {
        id: 'dex154',
        dexNumber: '154',
        title: "Bronzong",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/437.png",
        exclusive: "no",
    },
    {
        id: 'dex155',
        dexNumber: '155',
        title: "Axew",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/610.png",
        exclusive: "no",
    },
    {
        id: 'dex156',
        dexNumber: '156',
        title: "Fraxure",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/611.png",
        exclusive: "no",
    },
    {
        id: 'dex157',
        dexNumber: '157',
        title: "Haxorus",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/612.png",
        exclusive: "no",
    },
    {
        id: 'dex158',
        dexNumber: '158',
        title: "Mankey",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/056.png",
        exclusive: "no",
    },
    {
        id: 'dex159',
        dexNumber: '159',
        title: "Primeape",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/057.png",
        exclusive: "no",
    },
    {
        id: 'dex160',
        dexNumber: '160',
        title: "Annihilape",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1010.png",
        exclusive: "no",
    },
    {
        id: 'dex161',
        dexNumber: '161',
        title: "Meditite",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/307.png",
        exclusive: "no",
    },
    {
        id: 'dex162',
        dexNumber: '162',
        title: "Medicham",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/308.png",
        exclusive: "no",
    },
    {
        id: 'dex163',
        dexNumber: '163',
        title: "Riolu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/447.png",
        exclusive: "no",
    },
    {
        id: 'dex164',
        dexNumber: '164',
        title: "Lucario",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/448.png",
        exclusive: "no",
    },
    {
        id: 'dex165',
        dexNumber: '165',
        title: "Charcadet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1003.png",
        exclusive: "no",
    },
    {
        id: 'dex166',
        dexNumber: '166',
        title: "Armarouge",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1004.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex167',
        dexNumber: '167',
        title: "Ceruledge",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1005.png",
        exclusive: "Violet",
    },
    {
        id: 'dex168',
        dexNumber: '168',
        title: "Barboach",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/339.png",
        exclusive: "no",
    },
    {
        id: 'dex169',
        dexNumber: '169',
        title: "Whiscash",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/340.png",
        exclusive: "no",
    },
    {
        id: 'dex170',
        dexNumber: '170',
        title: "Tadbulb",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/940.png",
        exclusive: "no",
    },
    {
        id: 'dex171',
        dexNumber: '171',
        title: "Bellibolt",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/941.png",
        exclusive: "no",
    },
    {
        id: 'dex172',
        dexNumber: '172',
        title: "Goomy",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/704.png",
        exclusive: "no",
    },
    {
        id: 'dex173',
        dexNumber: '173',
        title: "Sliggoo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/705.png",
        exclusive: "no",
    },
    {
        id: 'dex174',
        dexNumber: '174',
        title: "Goodra",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/706.png",
        exclusive: "no",
    },
    {
        id: 'dex175',
        dexNumber: '175',
        title: "Croagunk",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/453.png",
        exclusive: "no",
    },
    {
        id: 'dex176',
        dexNumber: '176',
        title: "Toxicroak",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/454.png",
        exclusive: "no",
    },
    {
        id: 'dex177',
        dexNumber: '177',
        title: "Wattrel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/957.png",
        exclusive: "no",
    },
    {
        id: 'dex178',
        dexNumber: '178',
        title: "Kilowattrel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/958.png",
        exclusive: "no",
    },
    {
        id: 'dex179',
        dexNumber: '179',
        title: "Eevee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/133.png",
        exclusive: "no",
    },
    {
        id: 'dex180',
        dexNumber: '180',
        title: "Vaporeon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/134.png",
        exclusive: "no",
    },
    {
        id: 'dex181',
        dexNumber: '181',
        title: "Jolteon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/135.png",
        exclusive: "no",
    },
    {
        id: 'dex182',
        dexNumber: '182',
        title: "Flareon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/136.png",
        exclusive: "no",
    },
    {
        id: 'dex183',
        dexNumber: '183',
        title: "Espeon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/196.png",
        exclusive: "no",
    },
    {
        id: 'dex184',
        dexNumber: '184',
        title: "Umbreon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/197.png",
        exclusive: "no",
    },
    {
        id: 'dex185',
        dexNumber: '185',
        title: "Leafeon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/470.png",
        exclusive: "no",
    },
    {
        id: 'dex186',
        dexNumber: '186',
        title: "Glaceon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/471.png",
        exclusive: "no",
    },
    {
        id: 'dex187',
        dexNumber: '187',
        title: "Sylveon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/700.png",
        exclusive: "no",
    },
    {
        id: 'dex188',
        dexNumber: '188',
        title: "Dunsparce",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/206.png",
        exclusive: "no",
    },
    {
        id: 'dex189',
        dexNumber: '189',
        title: "Dudunsparce",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/917.png",
        exclusive: "no",
    },
    {
        id: 'dex190',
        dexNumber: '190',
        title: "Deerling",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/585.png",
        exclusive: "no",
    },
    {
        id: 'dex191',
        dexNumber: '191',
        title: "Sawsbuck",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/586.png",
        exclusive: "no",
    },
    {
        id: 'dex192',
        dexNumber: '192',
        title: "Girafarig",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/203.png",
        exclusive: "no",
    },
    {
        id: 'dex193',
        dexNumber: '193',
        title: "Farigiraf",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/928.png",
        exclusive: "no",
    },
    {
        id: 'dex194',
        dexNumber: '194',
        title: "Grimer",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/088.png",
        exclusive: "no",
    },
    {
        id: 'dex195',
        dexNumber: '195',
        title: "Muk",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/089.png",
        exclusive: "no",
    },
    {
        id: 'dex196',
        dexNumber: '196',
        title: "Maschiff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/972.png",
        exclusive: "no",
    },
    {
        id: 'dex197',
        dexNumber: '197',
        title: "Mabosstiff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/973.png",
        exclusive: "no",
    },
    {
        id: 'dex198',
        dexNumber: '198',
        title: "Toxel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/848.png",
        exclusive: "no",
    },
    {
        id: 'dex199',
        dexNumber: '199',
        title: "Toxtricity",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/849.png",
        exclusive: "no",
    },
    {
        id: 'dex200',
        dexNumber: '200',
        title: "Dedenne",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/702.png",
        exclusive: "no",
    },
    {
        id: 'dex201',
        dexNumber: '201',
        title: "Pachirisu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/417.png",
        exclusive: "no",
    },
    {
        id: 'dex202',
        dexNumber: '202',
        title: "Shroodle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/968.png",
        exclusive: "no",
    },
    {
        id: 'dex203',
        dexNumber: '203',
        title: "Grafaiai",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/969.png",
        exclusive: "no",
    },
    {
        id: 'dex204',
        dexNumber: '204',
        title: "Stantler",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/234.png",
        exclusive: "no",
    },
    {
        id: 'dex205',
        dexNumber: '205',
        title: "Foongus",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/590.png",
        exclusive: "no",
    },
    {
        id: 'dex206',
        dexNumber: '206',
        title: "Amoonguss",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/591.png",
        exclusive: "no",
    },
    {
        id: 'dex207',
        dexNumber: '207',
        title: "Voltorb",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/100.png",
        exclusive: "no",
    },
    {
        id: 'dex208',
        dexNumber: '208',
        title: "Electrode",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/101.png",
        exclusive: "no",
    },
    {
        id: 'dex209',
        dexNumber: '209',
        title: "Magnemite",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/081.png",
        exclusive: "no",
    },
    {
        id: 'dex210',
        dexNumber: '210',
        title: "Magneton",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/082.png",
        exclusive: "no",
    },
    {
        id: 'dex211',
        dexNumber: '211',
        title: "Magnezone",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/462.png",
        exclusive: "no",
    },
    {
        id: 'dex212',
        dexNumber: '212',
        title: "Ditto",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/132.png",
        exclusive: "no",
    },
    {
        id: 'dex213',
        dexNumber: '213',
        title: "Growlithe",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/058.png",
        exclusive: "no",
    },
    {
        id: 'dex214',
        dexNumber: '214',
        title: "Arcanine",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/059.png",
        exclusive: "no",
    },
    {
        id: 'dex215',
        dexNumber: '215',
        title: "Teddiursa",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/216.png",
        exclusive: "no",
    },
    {
        id: 'dex216',
        dexNumber: '216',
        title: "Ursaring",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/217.png",
        exclusive: "no",
    },
    {
        id: 'dex217',
        dexNumber: '217',
        title: "Zangoose",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/335.png",
        exclusive: "no",
    },
    {
        id: 'dex218',
        dexNumber: '218',
        title: "Seviper",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/336.png",
        exclusive: "no",
    },
    {
        id: 'dex219',
        dexNumber: '219',
        title: "Swablu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/333.png",
        exclusive: "no",
    },
    {
        id: 'dex220',
        dexNumber: '220',
        title: "Altaria",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/334.png",
        exclusive: "no",
    },
    {
        id: 'dex221',
        dexNumber: '221',
        title: "Skiddo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/672.png",
        exclusive: "no",
    },
    {
        id: 'dex222',
        dexNumber: '222',
        title: "Gogoat",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/673.png",
        exclusive: "no",
    },
    {
        id: 'dex223',
        dexNumber: '223',
        title: "Tauros",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/128-p.png",
        exclusive: "no",
    },
    {
        id: 'dex224',
        dexNumber: '224',
        title: "Litleo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/667.png",
        exclusive: "no",
    },
    {
        id: 'dex225',
        dexNumber: '225',
        title: "Pyroar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/668.png",
        exclusive: "no",
    },
    {
        id: 'dex226',
        dexNumber: '226',
        title: "Stunky",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/434.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex227',
        dexNumber: '227',
        title: "Skuntank",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/435.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex228',
        dexNumber: '228',
        title: "Zorua",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/570.png",
        exclusive: "no",
    },
    {
        id: 'dex229',
        dexNumber: '229',
        title: "Zoroark",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/571.png",
        exclusive: "no",
    },
    {
        id: 'dex230',
        dexNumber: '230',
        title: "Sneasel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/215.png",
        exclusive: "no",
    },
    {
        id: 'dex231',
        dexNumber: '231',
        title: "Weavile",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/461.png",
        exclusive: "no",
    },
    {
        id: 'dex232',
        dexNumber: '232',
        title: "Murkrow",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/198.png",
        exclusive: "no",
    },
    {
        id: 'dex233',
        dexNumber: '233',
        title: "Honchkrow",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/430.png",
        exclusive: "no",
    },
    {
        id: 'dex234',
        dexNumber: '234',
        title: "Gothita",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/574.png",
        exclusive: "no",
    },
    {
        id: 'dex235',
        dexNumber: '235',
        title: "Gothorita",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/575.png",
        exclusive: "no",
    },
    {
        id: 'dex236',
        dexNumber: '236',
        title: "Gothitelle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/576.png",
        exclusive: "no",
    },
    {
        id: 'dex237',
        dexNumber: '237',
        title: "Sinistea",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/854.png",
        exclusive: "no",
    },
    {
        id: 'dex238',
        dexNumber: '238',
        title: "Polteageist",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/855.png",
        exclusive: "no",
    },
    {
        id: 'dex239',
        dexNumber: '239',
        title: "Mimikyu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/778.png",
        exclusive: "no",
    },
    {
        id: 'dex240',
        dexNumber: '240',
        title: "Klefki",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/707.png",
        exclusive: "no",
    },
    {
        id: 'dex241',
        dexNumber: '241',
        title: "Indeedee",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/876.png",
        exclusive: "no",
    },
    {
        id: 'dex242',
        dexNumber: '242',
        title: "Bramblin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/974.png",
        exclusive: "no",
    },
    {
        id: 'dex243',
        dexNumber: '243',
        title: "Brambleghast",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/975.png",
        exclusive: "no",
    },
    {
        id: 'dex244',
        dexNumber: '244',
        title: "Toedscool",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1006.png",
        exclusive: "no",
    },
    {
        id: 'dex245',
        dexNumber: '245',
        title: "Toedscruel",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1007.png",
        exclusive: "no",
    },
    {
        id: 'dex246',
        dexNumber: '246',
        title: "Tropius",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/357.png",
        exclusive: "no",
    },
    {
        id: 'dex247',
        dexNumber: '247',
        title: "Fomantis",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/753.png",
        exclusive: "no",
    },
    {
        id: 'dex248',
        dexNumber: '248',
        title: "Lurantis",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/754.png",
        exclusive: "no",
    },
    {
        id: 'dex249',
        dexNumber: '249',
        title: "Klawf",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/962.png",
        exclusive: "no",
    },
    {
        id: 'dex250',
        dexNumber: '250',
        title: "Capsakid",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/938.png",
        exclusive: "no",
    },
    {
        id: 'dex251',
        dexNumber: '251',
        title: "Scovillain",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/939.png",
        exclusive: "no",
    },
    {
        id: 'dex252',
        dexNumber: '252',
        title: "Cacnea",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/331.png",
        exclusive: "no",
    },
    {
        id: 'dex253',
        dexNumber: '253',
        title: "Cacturne",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/332.png",
        exclusive: "no",
    },
    {
        id: 'dex254',
        dexNumber: '254',
        title: "Rellor",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/922.png",
        exclusive: "no",
    },
    {
        id: 'dex255',
        dexNumber: '255',
        title: "Rabsca",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/923.png",
        exclusive: "no",
    },
    {
        id: 'dex256',
        dexNumber: '256',
        title: "Venonat",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/048.png",
        exclusive: "no",
    },
    {
        id: 'dex257',
        dexNumber: '257',
        title: "Venomoth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/049.png",
        exclusive: "no",
    },
    {
        id: 'dex258',
        dexNumber: '258',
        title: "Pineco",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/204.png",
        exclusive: "no",
    },
    {
        id: 'dex259',
        dexNumber: '259',
        title: "Forretress",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/205.png",
        exclusive: "no",
    },
    {
        id: 'dex260',
        dexNumber: '260',
        title: "Scyther",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/123.png",
        exclusive: "no",
    },
    {
        id: 'dex261',
        dexNumber: '261',
        title: "Scizor",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/212.png",
        exclusive: "no",
    },
    {
        id: 'dex262',
        dexNumber: '262',
        title: "Heracross",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/214.png",
        exclusive: "no",
    },
    {
        id: 'dex263',
        dexNumber: '263',
        title: "Flittle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/926.png",
        exclusive: "no",
    },
    {
        id: 'dex264',
        dexNumber: '264',
        title: "Espathra",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/927.png",
        exclusive: "no",
    },
    {
        id: 'dex265',
        dexNumber: '265',
        title: "Hippopotas",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/449.png",
        exclusive: "no",
    },
    {
        id: 'dex266',
        dexNumber: '266',
        title: "Hippowdon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/450.png",
        exclusive: "no",
    },
    {
        id: 'dex267',
        dexNumber: '267',
        title: "Sandile",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/551.png",
        exclusive: "no",
    },
    {
        id: 'dex268',
        dexNumber: '268',
        title: "Krokorok",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/552.png",
        exclusive: "no",
    },
    {
        id: 'dex269',
        dexNumber: '269',
        title: "Krookodile",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/553.png",
        exclusive: "no",
    },
    {
        id: 'dex270',
        dexNumber: '270',
        title: "Silicobra",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/843.png",
        exclusive: "no",
    },
    {
        id: 'dex271',
        dexNumber: '271',
        title: "Sandaconda",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/844.png",
        exclusive: "no",
    },
    {
        id: 'dex272',
        dexNumber: '272',
        title: "Mudbray",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/749.png",
        exclusive: "no",
    },
    {
        id: 'dex273',
        dexNumber: '273',
        title: "Mudsdale",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/750.png",
        exclusive: "no",
    },
    {
        id: 'dex274',
        dexNumber: '274',
        title: "Larvesta",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/636.png",
        exclusive: "no",
    },
    {
        id: 'dex275',
        dexNumber: '275',
        title: "Volcarona",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/637.png",
        exclusive: "no",
    },
    {
        id: 'dex276',
        dexNumber: '276',
        title: "Bagon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/371.png",
        exclusive: "Violet",
    },
    {
        id: 'dex277',
        dexNumber: '277',
        title: "Shelgon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/372.png",
        exclusive: "Violet",
    },
    {
        id: 'dex278',
        dexNumber: '278',
        title: "Salamence",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/373.png",
        exclusive: "Violet",
    },
    {
        id: 'dex279',
        dexNumber: '279',
        title: "Tinkatink",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1000.png",
        exclusive: "no",
    },
    {
        id: 'dex280',
        dexNumber: '280',
        title: "Tinkatuff",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1001.png",
        exclusive: "no",
    },
    {
        id: 'dex281',
        dexNumber: '281',
        title: "Tinkaton",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1002.png",
        exclusive: "no",
    },
    {
        id: 'dex282',
        dexNumber: '282',
        title: "Hatenna",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/856.png",
        exclusive: "no",
    },
    {
        id: 'dex283',
        dexNumber: '283',
        title: "Hattrem",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/857.png",
        exclusive: "no",
    },
    {
        id: 'dex284',
        dexNumber: '284',
        title: "Hatterene",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/858.png",
        exclusive: "no",
    },
    {
        id: 'dex285',
        dexNumber: '285',
        title: "Impidimp",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/859.png",
        exclusive: "no",
    },
    {
        id: 'dex286',
        dexNumber: '286',
        title: "Morgrem",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/860.png",
        exclusive: "no",
    },
    {
        id: 'dex287',
        dexNumber: '287',
        title: "Grimmsnarl",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/861.png",
        exclusive: "no",
    },
    {
        id: 'dex288',
        dexNumber: '288',
        title: "Wiglett",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/929.png",
        exclusive: "no",
    },
    {
        id: 'dex289',
        dexNumber: '289',
        title: "Wugtrio",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/930.png",
        exclusive: "no",
    },
    {
        id: 'dex290',
        dexNumber: '290',
        title: "Bombirdier",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/959.png",
        exclusive: "no",
    },
    {
        id: 'dex291',
        dexNumber: '291',
        title: "Finizen",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/933.png",
        exclusive: "no",
    },
    {
        id: 'dex292',
        dexNumber: '292',
        title: "Palafin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/934.png",
        exclusive: "no",
    },
    {
        id: 'dex293',
        dexNumber: '293',
        title: "Varoom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/942.png",
        exclusive: "no",
    },
    {
        id: 'dex294',
        dexNumber: '294',
        title: "Revavroom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/943.png",
        exclusive: "no",
    },
    {
        id: 'dex295',
        dexNumber: '295',
        title: "Cyclizar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/953.png",
        exclusive: "no",
    },
    {
        id: 'dex296',
        dexNumber: '296',
        title: "Orthworm",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/944.png",
        exclusive: "no",
    },
    {
        id: 'dex297',
        dexNumber: '297',
        title: "Sableye",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/302.png",
        exclusive: "no",
    },
    {
        id: 'dex298',
        dexNumber: '298',
        title: "Shuppet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/353.png",
        exclusive: "no",
    },
    {
        id: 'dex299',
        dexNumber: '299',
        title: "Banette",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/354.png",
        exclusive: "no",
    },
    {
        id: 'dex300',
        dexNumber: '300',
        title: "Falinks",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/870.png",
        exclusive: "no",
    },
    {
        id: 'dex301',
        dexNumber: '301',
        title: "Hawlucha",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/701.png",
        exclusive: "no",
    },
    {
        id: 'dex302',
        dexNumber: '302',
        title: "Spiritomb",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/442.png",
        exclusive: "no",
    },
    {
        id: 'dex303',
        dexNumber: '303',
        title: "Noibat",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/714.png",
        exclusive: "no",
    },
    {
        id: 'dex304',
        dexNumber: '304',
        title: "Noivern",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/715.png",
        exclusive: "no",
    },
    {
        id: 'dex305',
        dexNumber: '305',
        title: "Dreepy",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/885.png",
        exclusive: "Violet",
    },
    {
        id: 'dex306',
        dexNumber: '306',
        title: "Drakloak",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/886.png",
        exclusive: "Violet",
    },
    {
        id: 'dex307',
        dexNumber: '307',
        title: "Dragapult",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/887.png",
        exclusive: "Violet",
    },
    {
        id: 'dex308',
        dexNumber: '308',
        title: "Glimmet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/966.png",
        exclusive: "no",
    },
    {
        id: 'dex309',
        dexNumber: '309',
        title: "Glimmora",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/967.png",
        exclusive: "no",
    },
    {
        id: 'dex310',
        dexNumber: '310',
        title: "Rotom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/479.png",
        exclusive: "no",
    },
    {
        id: 'dex311',
        dexNumber: '311',
        title: "Greavard",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/924.png",
        exclusive: "no",
    },
    {
        id: 'dex312',
        dexNumber: '312',
        title: "Houndstone",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/925.png",
        exclusive: "no",
    },
    {
        id: 'dex313',
        dexNumber: '313',
        title: "Oranguru",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/765.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex314',
        dexNumber: '314',
        title: "Passimian",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/766.png",
        exclusive: "Violet",
    },
    {
        id: 'dex315',
        dexNumber: '315',
        title: "Komala",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/775.png",
        exclusive: "no",
    },
    {
        id: 'dex316',
        dexNumber: '316',
        title: "Larvitar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/246.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex317',
        dexNumber: '317',
        title: "Pupitar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/247.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex318',
        dexNumber: '318',
        title: "Tyranitar",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/248.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex319',
        dexNumber: '319',
        title: "Stonjourner",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/874.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex320',
        dexNumber: '320',
        title: "Eiscue",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/875.png",
        exclusive: "Violet",
    },
    {
        id: 'dex321',
        dexNumber: '321',
        title: "Pincurchin",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/871.png",
        exclusive: "no",
    },
    {
        id: 'dex322',
        dexNumber: '322',
        title: "Sandygast",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/769.png",
        exclusive: "no",
    },
    {
        id: 'dex323',
        dexNumber: '323',
        title: "Palossand",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/770.png",
        exclusive: "no",
    },
    {
        id: 'dex324',
        dexNumber: '324',
        title: "Slowpoke",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/079.png",
        exclusive: "no",
    },
    {
        id: 'dex325',
        dexNumber: '325',
        title: "Slowbro",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/080.png",
        exclusive: "no",
    },
    {
        id: 'dex326',
        dexNumber: '326',
        title: "Slowking",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/199.png",
        exclusive: "no",
    },
    {
        id: 'dex327',
        dexNumber: '327',
        title: "Shellos",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/422.png",
        exclusive: "no",
    },
    {
        id: 'dex328',
        dexNumber: '328',
        title: "Gastrodon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/423.png",
        exclusive: "no",
    },
    {
        id: 'dex329',
        dexNumber: '329',
        title: "Shellder",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/090.png",
        exclusive: "no",
    },
    {
        id: 'dex330',
        dexNumber: '330',
        title: "Cloyster",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/091.png",
        exclusive: "no",
    },
    {
        id: 'dex331',
        dexNumber: '331',
        title: "Qwilfish",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/211.png",
        exclusive: "no",
    },
    {
        id: 'dex332',
        dexNumber: '332',
        title: "Luvdisc",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/370.png",
        exclusive: "no",
    },
    {
        id: 'dex333',
        dexNumber: '333',
        title: "Finneon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/456.png",
        exclusive: "no",
    },
    {
        id: 'dex334',
        dexNumber: '334',
        title: "Lumineon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/457.png",
        exclusive: "no",
    },
    {
        id: 'dex335',
        dexNumber: '335',
        title: "Bruxish",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/779.png",
        exclusive: "no",
    },
    {
        id: 'dex336',
        dexNumber: '336',
        title: "Alomomola",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/594.png",
        exclusive: "no",
    },
    {
        id: 'dex337',
        dexNumber: '337',
        title: "Skrelp",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/690.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex338',
        dexNumber: '338',
        title: "Dragalge",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/691.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex339',
        dexNumber: '339',
        title: "Clauncher",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/692.png",
        exclusive: "Violet",
    },
    {
        id: 'dex340',
        dexNumber: '340',
        title: "Clawitzer",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/693.png",
        exclusive: "Violet",
    },
    {
        id: 'dex341',
        dexNumber: '341',
        title: "Tynamo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/602.png",
        exclusive: "no",
    },
    {
        id: 'dex342',
        dexNumber: '342',
        title: "Eelektrik",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/603.png",
        exclusive: "no",
    },
    {
        id: 'dex343',
        dexNumber: '343',
        title: "Eelektross",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/604.png",
        exclusive: "no",
    },
    {
        id: 'dex344',
        dexNumber: '344',
        title: "Mareanie",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/747.png",
        exclusive: "no",
    },
    {
        id: 'dex345',
        dexNumber: '345',
        title: "Toxapex",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/748.png",
        exclusive: "no",
    },
    {
        id: 'dex346',
        dexNumber: '346',
        title: "Flamigo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/961.png",
        exclusive: "no",
    },
    {
        id: 'dex347',
        dexNumber: '347',
        title: "Dratini",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/147.png",
        exclusive: "no",
    },
    {
        id: 'dex348',
        dexNumber: '348',
        title: "Dragonair",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/148.png",
        exclusive: "no",
    },
    {
        id: 'dex349',
        dexNumber: '349',
        title: "Dragonite",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/149.png",
        exclusive: "no",
    },
    {
        id: 'dex350',
        dexNumber: '350',
        title: "Snom",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/872.png",
        exclusive: "no",
    },
    {
        id: 'dex351',
        dexNumber: '351',
        title: "Frosmoth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/873.png",
        exclusive: "no",
    },
    {
        id: 'dex352',
        dexNumber: '352',
        title: "Snover",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/459.png",
        exclusive: "no",
    },
    {
        id: 'dex353',
        dexNumber: '353',
        title: "Abomasnow",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/460.png",
        exclusive: "no",
    },
    {
        id: 'dex354',
        dexNumber: '354',
        title: "Delibird",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/225.png",
        exclusive: "no",
    },
    {
        id: 'dex355',
        dexNumber: '355',
        title: "Cubchoo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/613.png",
        exclusive: "no",
    },
    {
        id: 'dex356',
        dexNumber: '356',
        title: "Beartic",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/614.png",
        exclusive: "no",
    },
    {
        id: 'dex357',
        dexNumber: '357',
        title: "Snorunt",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/361.png",
        exclusive: "no",
    },
    {
        id: 'dex358',
        dexNumber: '358',
        title: "Glalie",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/362.png",
        exclusive: "no",
    },
    {
        id: 'dex359',
        dexNumber: '359',
        title: "Froslass",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/478.png",
        exclusive: "no",
    },
    {
        id: 'dex360',
        dexNumber: '360',
        title: "Cryogonal",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/615.png",
        exclusive: "no",
    },
    {
        id: 'dex361',
        dexNumber: '361',
        title: "Cetoddle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/947.png",
        exclusive: "no",
    },
    {
        id: 'dex362',
        dexNumber: '362',
        title: "Cetitan",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/948.png",
        exclusive: "no",
    },
    {
        id: 'dex363',
        dexNumber: '363',
        title: "Bergmite",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/712.png",
        exclusive: "no",
    },
    {
        id: 'dex364',
        dexNumber: '364',
        title: "Avalugg",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/713.png",
        exclusive: "no",
    },
    {
        id: 'dex365',
        dexNumber: '365',
        title: "Rufflet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/627.png",
        exclusive: "no",
    },
    {
        id: 'dex366',
        dexNumber: '366',
        title: "Braviary",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/628.png",
        exclusive: "no",
    },
    {
        id: 'dex367',
        dexNumber: '367',
        title: "Pawniard",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/624.png",
        exclusive: "no",
    },
    {
        id: 'dex368',
        dexNumber: '368',
        title: "Bisharp",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/625.png",
        exclusive: "no",
    },
    {
        id: 'dex369',
        dexNumber: '369',
        title: "Kingambit",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/1008.png",
        exclusive: "no",
    },
    {
        id: 'dex370',
        dexNumber: '370',
        title: "Deino",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/633.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex371',
        dexNumber: '371',
        title: "Zweilous",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/634.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex372',
        dexNumber: '372',
        title: "Hydreigon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/635.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex373',
        dexNumber: '373',
        title: "Veluza",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/932.png",
        exclusive: "no",
    },
    {
        id: 'dex374',
        dexNumber: '374',
        title: "Dondozo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/931.png",
        exclusive: "no",
    },
    {
        id: 'dex375',
        dexNumber: '375',
        title: "Tatsugiri",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/952.png",
        exclusive: "no",
    },
    {
        id: 'dex376',
        dexNumber: '376',
        title: "Great Tusk",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/978.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex377',
        dexNumber: '377',
        title: "Scream Tail",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/982.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex378',
        dexNumber: '378',
        title: "Brute Bonnet",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/979.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex379',
        dexNumber: '379',
        title: "Flutter Mane",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/983.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex380',
        dexNumber: '380',
        title: "Slither Wing",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/984.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex381',
        dexNumber: '381',
        title: "Sandy Shocks",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/981.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex382',
        dexNumber: '382',
        title: "Iron Treads",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/986.png",
        exclusive: "Violet",
    },
    {
        id: 'dex383',
        dexNumber: '383',
        title: "Iron Bundle",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/992.png",
        exclusive: "Violet",
    },
    {
        id: 'dex384',
        dexNumber: '384',
        title: "Iron Hands",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/989.png",
        exclusive: "Violet",
    },
    {
        id: 'dex385',
        dexNumber: '385',
        title: "Iron Jugulis",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/990.png",
        exclusive: "Violet",
    },
    {
        id: 'dex386',
        dexNumber: '386',
        title: "Iron Moth",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/988.png",
        exclusive: "Violet",
    },
    {
        id: 'dex387',
        dexNumber: '387',
        title: "Iron Thorns",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/991.png",
        exclusive: "Violet",
    },
    {
        id: 'dex388',
        dexNumber: '388',
        title: "Frigibax",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/949.png",
        exclusive: "no",
    },
    {
        id: 'dex389',
        dexNumber: '389',
        title: "Arctibax",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/950.png",
        exclusive: "no",
    },
    {
        id: 'dex390',
        dexNumber: '390',
        title: "Baxcalibur",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/951.png",
        exclusive: "no",
    },
    {
        id: 'dex391',
        dexNumber: '391',
        title: "Gimmighoul",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/976.png",
        exclusive: "no",
    },
    {
        id: 'dex392',
        dexNumber: '392',
        title: "Gholdengo",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/977.png",
        exclusive: "no",
    },
    {
        id: 'dex393',
        dexNumber: '393',
        title: "Wo-Chien",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/996.png",
        exclusive: "no",
    },
    {
        id: 'dex394',
        dexNumber: '394',
        title: "Chien-Pao",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/995.png",
        exclusive: "no",
    },
    {
        id: 'dex395',
        dexNumber: '395',
        title: "Ting-Lu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/994.png",
        exclusive: "no",
    },
    {
        id: 'dex396',
        dexNumber: '396',
        title: "Chi-Yu",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/997.png",
        exclusive: "no",
    },
    {
        id: 'dex397',
        dexNumber: '397',
        title: "Roaring Moon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/985.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex398',
        dexNumber: '398',
        title: "Iron Valiant",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/993.png",
        exclusive: "Violet",
    },
    {
        id: 'dex399',
        dexNumber: '399',
        title: "Koraidon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/998.png",
        exclusive: "Scarlet",
    },
    {
        id: 'dex400',
        dexNumber: '400',
        title: "Miraidon",
        img: "https://www.serebii.net/scarletviolet/pokemon/small/999.png",
        exclusive: "Violet",
    },
    
]
module.exports = pokedex